verify-core/verify/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.hello_world, name='hello_world'),
    path('events/', views.EventListView.as_view(), name='events'),
    path('events/<int:pk>/validate', views.validate_event_chain, name='validate'),
    path('events/<username>', views.verifier_detail_view, name='verifier_detail'),
    path('request_list/', views.RequestListView.as_view(), name='request_list'),
    path('request_list/<int:pk>/request_info_list', views.request_info_list, name='request_info_list'),
    path('add_event/', views.add_event, name='add_event'),
    path('add_work_event/', views.add_work_event, name='add_work_event'),
    path('add_education_event/', views.add_education_event, name='add_education_event'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('profile/', views.ProfileListView.as_view(), name='profile'),
    path('requests/', views.RequesterListView.as_view(), name='requests'),
    path('requests/<username>', views.requester_detail_view, name='requester_detail'),
    path('requests/<int:pk>/verify_event', views.verify_event, name='verify_event'),
    path('share_with/', views.ShareWithView.as_view(), name='share_with'),
    path('doc_share_with/', views.DocumentView.as_view(), name='doc_share_with'),
    path('share_with/<int:pk>/share', views.share, name='share'),
    path('doc_share_with/<int:pk>/doc_share', views.document_share, name='doc_share'),
    path('doc_link_with/<int:pk>/doc_link', views.document_link, name='doc_link'),
    path('review/<username>', views.requester_detail_view, name='requester_detail'),
    path('review/', views.ReviewListView.as_view(), name='review'),
    path('actions/', views.ActionsListView.as_view(), name='actions'),
    path('upload/', views.upload, name='upload'),
    path('request_info/', views.request_info, name='request_info'),
    path('view_documents/<int:pk>', views.view_document, name='view_document'),
]

verify-core/verifypoc/urls.py
from django.contrib import admin
from django.urls import include, path
from verify import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('verify.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.StandardSignUpView.as_view(), name='signup'),
    path('accounts/signup/requester/', views.RequesterSignUpView.as_view(), name='requester_signup'),
    path('accounts/signup/verifier/', views.VerifierSignUpView.as_view(), name='verifier_signup'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

verify-core/verify/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType


class Actions(models.Model):
    ADD_LIVING_EVENT = 'Added Living Event'
    ADD_WORK_EVENT = 'Added Work Event'
    ADD_EDUCATION_EVENT = 'Added Education Event'
    ADD_DOCUMENT_EVENT = 'Added Document'
    VERIFY_EVENT = 'Verified User Event'
    SHARE_EVENT = 'Shared Event'
    ACTION_TYPES = (
        (ADD_LIVING_EVENT, 'Living Event'),
        (ADD_WORK_EVENT, 'Work Event'),
        (ADD_EDUCATION_EVENT, 'Education Event'),
        (ADD_DOCUMENT_EVENT, 'DOCUMENT Event'),
        (VERIFY_EVENT, 'Verify event'),
        (SHARE_EVENT, 'Share Event'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    action_type = models.CharField(max_length=1, choices=ACTION_TYPES)
    date = models.DateTimeField(auto_now_add=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey()


class Businesses(models.Model):
    BUSINESS_TYPE = [
        ("ES", "Estate Agent"),
        ("WO", "Work Experience"),
    ]
    business_type = models.CharField(max_length=1,
                                     choices=BUSINESS_TYPE)
    business_name = models.CharField(max_length=50)

    def __str__(self):
        """String representing the living Item"""
        return self.business_name


def user_directory_path(instance, filename):
    return 'user_{0}/{1}/{2}'.format(instance.user,
                                     instance.document_type,
                                     filename)


class Document(models.Model):
    PASSPORT = 'Passport'
    DRIVING_LICENCE = 'Driving Licence'
    GAS_ELECTRIC_BILL = 'Gas or Electric Bill'
    EDUCATION_EVIDENCE = 'Education Evidence'
    DOCUMENT_TYPES = (
        (PASSPORT, 'Passport'),
        (DRIVING_LICENCE, 'Driving Licence'),
        (GAS_ELECTRIC_BILL, 'Gas or Electric Bill'),
        (EDUCATION_EVIDENCE, 'Education Evidence'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    document_type = models.CharField(max_length=30, choices=DOCUMENT_TYPES)
    date = models.DateTimeField(auto_now_add=True)
    document = models.FileField(upload_to=user_directory_path)
    shared_with = models.ForeignKey(
        Businesses,
        related_name='document_shared_with',
        default=None,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    action = GenericRelation(Actions)

    def __str__(self):
        """String representing the living Item"""
        return self.document


class Item(models.Model):
    """Model for Living Item"""
    LIVING = 'living'
    WORK = 'work'
    EDUCATION = 'education'
    EVENT_TYPES = (
        (LIVING, 'living'),
        (WORK, 'work'),
        (EDUCATION, 'education'),
    )
    event_type = models.CharField(max_length=30, choices=EVENT_TYPES)
    start_date = models.DateTimeField(
        help_text="The start date"
    )
    end_date = models.DateTimeField(
        help_text="The end Date"
    )
    address = models.CharField(
        help_text="The address of where you lived",
        max_length=200
    )
    verifier = models.ForeignKey(
        Businesses,
        related_name='living_verifier',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    is_verified = models.BooleanField(
        default=False
    )
    verified_by = models.ForeignKey(
        Businesses,
        related_name='living_verified_by',
        default=None,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    added_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    shared_with = models.ForeignKey(
        Businesses,
        related_name='living_shared_with',
        default=None,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    linked_docs = models.ForeignKey(
        Document,
        related_name='living_linked_docs',
        default=None,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    verified_hash = models.CharField(
        max_length=30,
        null=True,
        blank=True,
    )
    verified_unique_id = models.CharField(
        max_length=30,
        null=True,
        blank=True,
    )
    chain_index = models.IntegerField(
        null=True,
        blank=True,
    )
    verified_datetime = models.CharField(
        max_length=30,
        null=True,
        blank=True,
    )
    action = GenericRelation(Actions)

    def __str__(self):
        """String representing the living Item"""
        return self.address


class User(AbstractUser):
    is_requester = models.BooleanField(default=False)
    is_verifier = models.BooleanField(default=False)
    BUSINESS_TYPE = [
        ("ES", "Estate Agent"),
        ("WO", "Work Experience"),
    ]
    business_type = models.CharField(max_length=30,
                                     choices=BUSINESS_TYPE,
                                     null=True)
    business_name = models.CharField(max_length=50, null=True)
    unique_id = models.CharField(max_length=100)


class Profile(models.Model):
    """Extending user info"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    email_address = models.CharField(max_length=30, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Requests(models.Model):
    start_date = models.DateTimeField(
        help_text="The start date"
    )
    end_date = models.DateTimeField(
        help_text="The end Date"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='requests_user'
    )
    requester = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='requests_requester'
    )

verify-core/verify/forms.py
import datetime
from uuid import uuid4

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from .models import (User, Profile, Businesses, Document,
                     Item, Requests)


class EnterLivingForm(forms.Form):
    start_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        required=True,
        help_text="Enter the date you moved in",
    )
    end_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        required=True,
        help_text="Enter the date you moved out"
    )
    address = forms.CharField(
        required=True,
        help_text="Address of where you lived"
    )
    verifier = forms.ModelChoiceField(
        queryset=Businesses.objects.all().order_by('business_name')
    )

    def start_date_correct(self):
        data = self.cleaned_data['start_date']

        if data > datetime.date.today():
            raise ValidationError(_('Invalid date - in the future'))

        return data

    def end_date_correct(self, start_date_correct):
        data = self.cleaned_data['end_date']

        if data < start_date_correct:
            raise ValidationError(_('Invalid end date - before start date'))


class EnterWorkForm(forms.Form):
    start_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        required=True,
        help_text="Enter the date you moved in",
    )
    end_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        required=True,
        help_text="Enter the date you moved out"
    )
    work_place = forms.CharField(
        required=True,
        help_text="The place where you worked"
    )
    verifier = forms.ModelChoiceField(
        queryset=Businesses.objects.all().order_by('business_name')
    )

    def start_date_correct(self):
        data = self.cleaned_data['start_date']

        if data > datetime.date.today():
            raise ValidationError(_('Invalid date - in the future'))

        return data

    def end_date_correct(self, start_date_correct):
        data = self.cleaned_data['end_date']

        if data < start_date_correct:
            raise ValidationError(_('Invalid end date - before start date'))


class EnterEducationForm(forms.Form):
    start_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        required=True,
        help_text="Enter the date you started",
    )
    end_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        required=True,
        help_text="Enter the date you finished"
    )
    institution = forms.CharField(
        required=True,
        help_text="The place where you studied"
    )
    verifier = forms.ModelChoiceField(
        queryset=Businesses.objects.all().order_by('business_name')
    )

    def start_date_correct(self):
        data = self.cleaned_data['start_date']

        if data > datetime.date.today():
            raise ValidationError(_('Invalid date - in the future'))

        return data

    def end_date_correct(self, start_date_correct):
        data = self.cleaned_data['end_date']

        if data < start_date_correct:
            raise ValidationError(_('Invalid end date - before start date'))


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('location', 'birth_date')


class RequesterSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name',
                  'last_name', 'email',)

    def save(self):
        user = super().save(commit=False)
        unique_id = str(uuid4()).replace('-', '')
        user.is_requester = True
        user.unique_id = unique_id
        user.save()
        return user


class VerifierSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name',
                  'last_name', 'email',
                  'business_type', 'business_name')

    def save(self, commit=True):
        user = super().save(commit=False)
        unique_id = str(uuid4()).replace('-', '')
        user.is_verifier = True
        user.unique_id = unique_id
        if commit:
            user.save()
        return user


class ShareWithForm(forms.Form):
    share_with = forms.ModelChoiceField(queryset=Businesses.objects.all())


class RequestWithForm(forms.Form):
    share_with = forms.ModelChoiceField(queryset=Businesses.objects.all())


class LinkWithForm(forms.Form):
    link_with = forms.ModelChoiceField(queryset=Item.objects.none())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(LinkWithForm, self).__init__(*args, **kwargs)
        self.fields['link_with'].queryset = Item.objects.filter(added_by=self.user)


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document_type', 'document',)


class RequestForm(forms.ModelForm):
    start_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        }))
    end_date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker2'
        }))
    user = forms.ModelChoiceField(queryset=User.objects.filter(is_requester=True))

    class Meta:
        model = Requests
        fields = ('user', 'start_date', 'end_date')

verify-core/verify/templates/verify/actions_list.html
{% extends "base.html" %}

{% block content %}
<div class="titlebar-container">
  <div class="titlebar">
    <h1 class="title">Actions History</h1>
  </div>
</div>
  <br>
  {% if my_actions_list %}
  <ul>
    {% for object in my_actions_list %}
    <li>{{ object.action_type }} {{ object.date }}</li><br>
    {% endfor %}
  </ul>
  {% else %}
    <p>No Actions Yet</p>
  {% endif %}
{% endblock %}

verify-core/verify/templates/verify/document_share.html
{% extends "base.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col-8">
                <h3 class="mb-0">Share Event </h3>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="btn btn-default btn-lg" role="alert">
                Share with {{ form.share_with }}?
            </div>
            <div class="alert alert-warning" role="alert">
                Are you sure you want to share <strong>{{ object.document_type }}</strong> ?
            </div>
            <div class="row">
                <div class="col-4 offset-4">
                    <input type="submit" class="btn btn-default btn-lg" value="Share">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

verify-core/verify/templates/verify/event_added.html
{% extends "base.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <br>
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

verify-core/verify/templates/verify/failure.html
{% extends "base.html" %}

{% block content %}
  <h1>Sorry, that does not match what is in the chain</h1>
  {% load static %}
  <img src="{% static 'images/cat.png' %}" alt="Cat" style="width:555px;height:540px;">
{% endblock %}

verify-core/verify/templates/verify/livingitem_list.html
{% extends "base.html" %}

{% block content %}
<div class="titlebar-container">
  <div class="titlebar">
    <h1 class="title">Event List</h1>
  </div>
</div>
  <br>
  You have had {{ score.1 }}% of your events verified<br>
  Your Score is {{ score.0 }}!!
  <br><br>
  <h3>Places you have Lived</h3><br>
  {% if my_event_list %}
    <ul id="address-history">
    {% for object in my_event_list %}
      <li>
      {% if object.address %}
        {{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }}
        {% if object.linked_docs.document_type %}
        <br>Support Docs:
        {{ object.linked_docs.document_type }}
        {% endif %}
         {% if object.is_verified %}
            <br>Verified by:
                  <a href="{{ object.verified_by }}"> {{ object.verified_by }}</a>
           <span>&#9989;</span><br>
           <a href="{% url 'validate' object.id %}" class="btn btn-sm btn-info">validate</a><br><br>
         {% endif %}
      {% endif %}
      </li>
    {% endfor %}
    </ul>
    <li><a id="add-living-event" href="{% url 'add_event' %}">Add Living Event</a></li><br>
  {% else %}
    <p>You have not added any addresses</p>
     <li><a href="{% url 'add_event' %}">Add Living Event</a></li><br>
  {% endif %}
   <h3>Places you have Worked</h3><br>
  {% if work_history_list %}
    {% for object in work_history_list %}
      {% if object.address %}
        {{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }}
          {% if object.linked_docs.document_type %}
         <br>Support Docs:
         {{ object.linked_docs.document_type }}
         {% endif %}
          {% if object.is_verified %}
             <br>Verified by:
                   <a href="{{ object.verified_by }}"> {{ object.verified_by }}</a>
            <span>&#9989;</span><br>
            <a href="{% url 'validate' object.id %}" class="btn btn-sm btn-info">validate</a><br><br>
          {% endif %}
      {% endif %}
    {% endfor %}
    <li><a href="{% url 'add_work_event' %}">Add Work Event</a></li><br>
  {% else %}
    <p>You have not added any Work places</p>
     <li><a href="{% url 'add_work_event' %}">Add Work Event</a></li><br>
  {% endif %}
<h3>Education History</h3><br>
  {% if education_history_list %}
    {% for object in education_history_list %}
      {% if object.address %}
        {{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }}
          {% if object.linked_docs.document_type %}
         <br>Support Docs:
         {{ object.linked_docs.document_type }}
         {% endif %}
          {% if object.is_verified %}
            <br>Verified by:
                   <a href="{{ object.verified_by }}"> {{ object.verified_by }}</a>
            <span>&#9989;</span><br>
            <a href="{% url 'validate' object.id %}" class="btn btn-sm btn-info">validate</a><br><br>
          {% endif %}
      {% endif %}
    {% endfor %}
    <li><a href="{% url 'add_education_event' %}">Add Education Event</a></li><br>
  {% else %}
    <p>You have not added any Education Events</p>
     <li><a href="{% url 'add_education_event' %}">Add Education Event</a></li><br>
  {% endif %}
{% endblock %}

verify-core/verify/templates/verify/profile_list.html
{% extends "base.html" %}

{% block content %}
<div class="titlebar-container">
  <div class="titlebar">
    <h1 class="title">Profile</h1>
  </div>
</div>
  {% if my_profile_list %}
  <ul>
      {% for object in my_profile_list %}
      First Name: {{ object.first_name }}<br>
      Last Name: {{ object.last_name }}<br>
      Email: {{ object.email }}<br>
      {% endfor %}
      {% for object in profile_list %}
      {% if object.location %}
      <li>Location: {{ object.location }}</li>
      <li>DOB: {{ object.birth_date }}</li>
      {% endif %}
      {% endfor %}
    <br><li><a href="{% url 'update_profile' %}">Edit Profile</a></li>
  </ul>
  {% endif %}
{% endblock %}

verify-core/verify/templates/verify/request_info.html
{% extends "base.html" %}

{% block content %}
<div class="titlebar-container">
  <div class="titlebar">
    <h1 class="title">Request Items</h1>
  </div>
</div>
<div class="card">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col-8">
                <h3 class="mb-0">Request Info </h3>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="btn btn-default btn-lg" role="alert">
                <div class="input-group" id="user"</div>
                     {{ form.user }}
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                  {{ form.start_date }}
                    <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
                 <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                  {{ form.end_date }}
                    <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4 offset-4">
                    <input type="submit" class="btn btn-default btn-lg" value="Request">
                </div>
            </div>
        </form>
    </div>
</div>
<script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY',
    });
  });
</script>
<script>
  $(function () {
    $("#datetimepicker2").datetimepicker({
      format: 'DD/MM/YYYY',
    });
  });
</script>
{% endblock %}

verify-core/verify/templates/verify/requester_list.html
{% extends "base.html" %}

{% block content %}
<div class="titlebar-container">
  <div class="titlebar">
    <h1 class="title">Items to be Verified</h1>
  </div>
</div>
  <br>
  <h3>Living items to Verify</h3>
  {% if my_event_list %}
  <ul>
    {% for object in my_event_list %}
       {% if object.address %}
        <a href="{{ object.added_by }}">{{ object.added_by }}</a><br> {{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }} <a href="{% url 'verify_event' object.id %}" class="btn btn-sm btn-info">Verify</a><br><br>
      {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Nothing to verify</p><br>
  {% endif %}
   <h3>Work Items to verify</h3>
  {% if work_history_list %}
  <ul>
    {% for object in work_history_list %}
      {% if object.address %}
        <a href="{{ object.added_by }}">{{ object.added_by }}</a><br> {{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }} <a href="{% url 'verify_event' object.id %}" class="btn btn-sm btn-info">Verify</a><br><br>
      {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Nothing to verify</p><br>
  {% endif %}
  <h3>Education Items to verify</h3>
  {% if education_history_list %}
  <ul>
    {% for object in education_history_list %}
      {% if object.address %}
        <a href="{{ object.added_by }}">{{ object.added_by }}</a><br> {{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }} <a href="{% url 'verify_event' object.id %}" class="btn btn-sm btn-info">Verify</a><br><br>
      {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Nothing to verify</p><br>
  {% endif %}
{% endblock %}

verify-core/verify/templates/verify/reviewer_list.html
{% extends "base.html" %}

{% block content %}
<div class="titlebar-container">
  <div class="titlebar">
    <h1 class="title">Items Shared With You</h1>
  </div>
</div>
  <br>
  <h3>Living items that have been shared</h3>
  {% if my_event_list %}
    {% for object in my_event_list %}
       {% if object.address %}
        <a href="{{ object.added_by }}">{{ object.added_by }}</a><br>{{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }}
        {% if object.linked_docs.document_type %}
         <br>Support Docs:
         {{ object.linked_docs.document_type }}
         <a href="{% url 'view_document' object.linked_docs.id %}" class="btn btn-sm btn-info">view</a>
         {% endif %}
          {% if object.is_verified %}
            <br>Verified by: {{ object.verified_by }}
            <span>&#9989;</span>
          {% endif %}
          <br><br>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>Nothing has been shared</p><br>
  {% endif %}
   <h3>Work Items that have been shared</h3>
  {% if work_history_list %}
    {% for object in work_history_list %}
      {% if object.address %}
        <a href="{{ object.added_by }}">{{ object.added_by }}</a><br>{{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }}
        {% if object.linked_docs.document_type %}
         <br>Support Docs:
         {{ object.linked_docs.document_type }}
         <a href="{% url 'view_document' object.linked_docs.id %}" class="btn btn-sm btn-info">view</a>
         {% endif %}
          {% if object.is_verified %}
           <br>Verified by: {{ object.verified_by }}
            <span>&#9989;</span>
          {% endif %}
          <br><br>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>Nothing has been shared</p><br>
  {% endif %}
   <h3>Education Items that have been shared</h3>
  {% if education_history_list %}
    {% for object in education_history_list %}
      {% if object.address %}
        <a href="{{ object.added_by }}">{{ object.added_by }}</a><br>{{ object.address }} {{ object.start_date|date:"Y M d" }} - {{ object.end_date|date:"Y M d" }}
        {% if object.linked_docs.document_type %}
         <br>Support Docs:
         {{ object.linked_docs.document_type }}
         <a href="{% url 'view_document' object.linked_docs.id %}" class="btn btn-sm btn-info">view</a>
         {% endif %}
          {% if object.is_verified %}
           <br>Verified by: {{ object.verified_by }}
            <span>&#9989;</span>
          {% endif %}
          <br><br>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>Nothing has been shared</p><br>
  {% endif %}
  <h3>Documents that have been shared</h3>
  {% if document_list %}
    {% for object in document_list %}
      {% if object.document_type %}
       <a href="{{ object.user }}">{{ object.user }}</a><br>{{ object.document_type }} {{ object.date }}
       <a href="{% url 'view_document' object.id %}" class="btn btn-sm btn-info">view</a><br>
       <br>
      {% endif %}
    {% endfor %}
  {% else %}
    <p>Nothing has been shared</p><br>
  {% endif %}
{% endblock %}

verify-core/verify/templates/verify/success.html
{% extends "base.html" %}

{% block content %}
  <h1>Success, that matches the chain.</h1>
  {% load static %}
  <img src="{% static 'images/cat.png' %}" alt="Cat" style="width:555px;height:540px;">
{% endblock %}

verify-core/verify/templates/verify/verifier_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Title: {{ user.username }}</h1><br>

  <p><strong>First name:</strong> {{ user.first_name }}</></p>
  <p><strong>Second name:</strong> {{ user.last_name }}</p>
  <p><strong>Email:</strong> {{ user.email }}</p>
  <p><strong>Verifier:</strong> {{ user.is_verifier }}</p>

{% endblock %}